service: meetup-api-proxy

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, file(config.json):stage, 'dev'}
  region: ${opt:region, file(config.json):region, 'us-east-1'}

functions:
  call:
    handler: src/call.handler
    name: ${self:provider.stage}-${self:service}-call
    memorySize: 128
    events:
      - http:
          path: call
          method: any

plugins:
- serverless-offline # plugin to run the offline emulation
